# Generated by Django 5.1.6 on 2025-02-26 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Uzivatel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jmeno", models.CharField(max_length=100)),
                ("vek", models.IntegerField()),
                ("vyska", models.FloatField()),
                ("vaha", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Trenink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("gym", "Posilovna"), ("outdoor", "Outdoor")],
                        max_length=20,
                    ),
                ),
                ("doba", models.PositiveIntegerField()),
                ("pozn", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.uzivatel"
                    ),
                ),
            ],
        ),
    ]
