# Generated by Django 5.1.6 on 2025-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trenink",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
