# Generated by Django 5.1.6 on 2025-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_uzivatel_active_alter_uzivatel_groups_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uzivatel",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="uzivatele_skupiny", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="uzivatel",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="uzivatele_opravneni", to="auth.permission"
            ),
        ),
    ]
