# Generated by Django 5.1.6 on 2025-03-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_uzivatel_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uzivatel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
