# Generated by Django 5.1.6 on 2025-03-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_uzivatel_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uzivatel",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
