# Generated by Django 5.1.6 on 2025-03-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_uzivatel_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uzivatel",
            name="jmeno",
        ),
        migrations.AlterField(
            model_name="uzivatel",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
