# Generated by Django 5.1.6 on 2025-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_uzivatel_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trenink",
            name="type",
            field=models.CharField(
                choices=[("gym", "Posilovna"), ("workout", "Workout"), ("běh", "Běh")],
                max_length=20,
            ),
        ),
    ]
