# Generated by Django 5.1.6 on 2025-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_trenink_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trenink",
            name="nazev",
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
