# Generated by Django 5.1.6 on 2025-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_trenink_pozn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trenink",
            name="pozn",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
