# Generated by Django 5.1.6 on 2025-03-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_trenink_pozn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trenink",
            name="type",
            field=models.CharField(
                choices=[
                    ("gym", "Gym/Posilovna"),
                    ("Workout", "Workout"),
                    ("běh", "Běh"),
                    ("cyklo", "Kolo"),
                ],
                max_length=20,
            ),
        ),
    ]
