# Generated by Django 5.1.6 on 2025-03-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_trenink_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trenink",
            name="type",
            field=models.CharField(
                choices=[
                    ("Gym", "Gym/Posilovna"),
                    ("Workout", "Workout"),
                    ("Běh", "Běh"),
                    ("Cyklo", "Kolo"),
                    ("Míčovky", "Míčovky"),
                    ("Plavání", "Plavání"),
                    ("Běžky", "Běžky"),
                ],
                max_length=20,
            ),
        ),
    ]
